/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecteursRouteImport } from './routes/secteurs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecteursIndexRouteImport } from './routes/secteurs.index'
import { Route as SecteursSlugRouteImport } from './routes/secteurs.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursRoute = SecteursRouteImport.update({
  id: '/secteurs',
  path: '/secteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecteursIndexRoute = SecteursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecteursRoute,
} as any)
const SecteursSlugRoute = SecteursSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SecteursRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/secteurs': typeof SecteursRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/secteurs/': typeof SecteursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/secteurs': typeof SecteursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/secteurs': typeof SecteursRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/secteurs/$slug': typeof SecteursSlugRoute
  '/secteurs/': typeof SecteursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/secteurs'
    | '/sitemap.xml'
    | '/secteurs/$slug'
    | '/secteurs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitemap.xml' | '/secteurs/$slug' | '/secteurs'
  id:
    | '__root__'
    | '/'
    | '/secteurs'
    | '/sitemap.xml'
    | '/secteurs/$slug'
    | '/secteurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SecteursRoute: typeof SecteursRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs': {
      id: '/secteurs'
      path: '/secteurs'
      fullPath: '/secteurs'
      preLoaderRoute: typeof SecteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secteurs/': {
      id: '/secteurs/'
      path: '/'
      fullPath: '/secteurs/'
      preLoaderRoute: typeof SecteursIndexRouteImport
      parentRoute: typeof SecteursRoute
    }
    '/secteurs/$slug': {
      id: '/secteurs/$slug'
      path: '/$slug'
      fullPath: '/secteurs/$slug'
      preLoaderRoute: typeof SecteursSlugRouteImport
      parentRoute: typeof SecteursRoute
    }
  }
}

interface SecteursRouteChildren {
  SecteursSlugRoute: typeof SecteursSlugRoute
  SecteursIndexRoute: typeof SecteursIndexRoute
}

const SecteursRouteChildren: SecteursRouteChildren = {
  SecteursSlugRoute: SecteursSlugRoute,
  SecteursIndexRoute: SecteursIndexRoute,
}

const SecteursRouteWithChildren = SecteursRoute._addFileChildren(
  SecteursRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SecteursRoute: SecteursRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
